dados_padrao = {
    "ID": "",
    "Tipo": "",
    "SKU": "",
    "GTIN UPC EAN ISBN": "",
    "Nome": "",
    "Publicado": "",
    "Em Destaque": "",
    "Visibilidade no Catálogo": "",
    "Descrição Curta": "",
    "Descrição": "",
    "Data de Preço Promocional Começa em": "",
    "Data de Preço Promocional Termina em": "",
    "Status do Imposto": "",
    "Classe de Imposto": "",
    "Em Estoque": "",
    "Estoque": "",
    "Quantidade Baixa de Estoque": "",
    "São Permitidas Encomendas": "",
    "Vendido Individualmente": "",
    "Peso (kg)": "",
    "Comprimento (cm)": "",
    "Largura (cm)": "",
    "Altura (cm)": "",
    "Permitir Avaliações de Clientes": "",
    "Nota de Compra": "",
    "Preço Promocional": "",
    "Preço": "",
    "Categorias": "",
    "Tags": "",
    "Classe de Entrega": "",
    "Imagens": "",
    "Limite de Downloads": "",
    "Dias para Expirar o Download": "",
    "Ascendente": "",
    "Grupo de Produtos": "",
    "Upsells": "",
    "Venda Cruzada": "",
    "URL Externa": "",
    "Texto do Botão": "",
    "Posição": "",
    "Brands": "",
    "Nome do Atributo 1": "",
    "Valores do Atributo 1": "",
    "Visibilidade do Atributo 1": "",
    "Atributo Global 1": "",
    "Atributo Padrão 1": "",
    "Nome do Atributo 2": "",
    "Valores do Atributo 2": "",
    "Visibilidade do Atributo 2": "",
    "Atributo Global 2": "",
    "Atributo Padrão 2": ""
}
